[workspace]

members = [
    "hello_world",
    "scalar_types",
    "collections",
    "objects",
    "enums",
    "flow_control",
    "functions",
    "errors",
    "testing",
    "methods",
    "modularity",
]
